name: jest

on:
  pull_request:

jobs:
  jest:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    strategy:
      matrix:
        runner: [ubuntu-22.04]
        node: [20]
    name: build on node ${{ matrix.node }} ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: npm ci
        run: npm ci
      - name: build
        run: npm run build
      - name: start
        run: npm run start &
      - name: test
        run: npm run test
